# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

contains_cpp <- function(s, L) {
    .Call(`_fgRcppNorway_contains_cpp`, s, L)
}

extract_create_numcolumns_cpp <- function(s, DF, n) {
    .Call(`_fgRcppNorway_extract_create_numcolumns_cpp`, s, DF, n)
}

extract_create_intcolumns_cpp <- function(s, DF, n) {
    .Call(`_fgRcppNorway_extract_create_intcolumns_cpp`, s, DF, n)
}

extract_create_strcolumns_cpp <- function(s, DF, n) {
    .Call(`_fgRcppNorway_extract_create_strcolumns_cpp`, s, DF, n)
}

sp_params_Norway_fun_cpp <- function(species_parameters, species, location, dbh_class, leafstatus) {
    .Call(`_fgRcppNorway_sp_params_Norway_fun_cpp`, species_parameters, species, location, dbh_class, leafstatus)
}

top_ht_to_mean_ht_cpp <- function(param0_height, param1_height, top_ht) {
    .Call(`_fgRcppNorway_top_ht_to_mean_ht_cpp`, param0_height, param1_height, top_ht)
}

mean_ht_to_top_ht_cpp <- function(param0_height, param1_height, mean_ht) {
    .Call(`_fgRcppNorway_mean_ht_to_top_ht_cpp`, param0_height, param1_height, mean_ht)
}

eq_mean_ht_fun_cpp <- function(top_ht) {
    .Call(`_fgRcppNorway_eq_mean_ht_fun_cpp`, top_ht)
}

canopy_width_fun_cpp <- function(param0_cr_width, param1_cr_width, dbh) {
    .Call(`_fgRcppNorway_canopy_width_fun_cpp`, param0_cr_width, param1_cr_width, dbh)
}

canopy_depth_Norway_fun_cpp <- function(species, species_parameters, dbh, ht, focus = "tree") {
    .Call(`_fgRcppNorway_canopy_depth_Norway_fun_cpp`, species, species_parameters, dbh, ht, focus)
}

stem_volume_fonweban_cpp <- function(dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_volume_fonweban_cpp`, dbh, ht, species_parameters)
}

stem_volume_quebec_cpp <- function(dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_volume_quebec_cpp`, dbh, ht, species_parameters)
}

stem_volume_laasasenaho_cpp <- function(dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_volume_laasasenaho_cpp`, dbh, ht, species_parameters)
}

stem_volume_japanese_larch_japan_cpp <- function(dbh, ht) {
    .Call(`_fgRcppNorway_stem_volume_japanese_larch_japan_cpp`, dbh, ht)
}

stem_vol_andretreslag_fun_cpp <- function(species, dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_vol_andretreslag_fun_cpp`, species, dbh, ht, species_parameters)
}

stem_vol_NSNorway_fun_cpp <- function(location, dbh_class, dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_vol_NSNorway_fun_cpp`, location, dbh_class, dbh, ht, species_parameters)
}

stem_vol_SPNorway_fun_cpp <- function(location, dbh_class, dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_vol_SPNorway_fun_cpp`, location, dbh_class, dbh, ht, species_parameters)
}

stem_vol_BINorway_fun_cpp <- function(location, dbh_class, dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_vol_BINorway_fun_cpp`, location, dbh_class, dbh, ht, species_parameters)
}

stem_vol_Norway_fun_cpp <- function(species, location, dbh_class, dbh, ht, species_parameters) {
    .Call(`_fgRcppNorway_stem_vol_Norway_fun_cpp`, species, location, dbh_class, dbh, ht, species_parameters)
}

fg_rou_dataprep_Norway_cpp <- function(inputdata, fgr_constants, species_parameters, season = "winter", country = "fgr") {
    .Call(`_fgRcppNorway_fg_rou_dataprep_Norway_cpp`, inputdata, fgr_constants, species_parameters, season, country)
}

fg_tmc_dataprep_Norway_cpp <- function(inputdata, fgr_constants, species_parameters, season = "winter", country = "fgr") {
    .Call(`_fgRcppNorway_fg_tmc_dataprep_Norway_cpp`, inputdata, fgr_constants, species_parameters, season, country)
}

diam_base_fun_cpp <- function(dbh, ht, cr_depth) {
    .Call(`_fgRcppNorway_diam_base_fun_cpp`, dbh, ht, cr_depth)
}

drag_fun_cpp <- function(uguess, n_drag, c_drag, drag_upper_limit) {
    .Call(`_fgRcppNorway_drag_fun_cpp`, uguess, n_drag, c_drag, drag_upper_limit)
}

canopy_breadth_fun_cpp <- function(cr_width, uguess, n_drag, c_drag, drag_upper_limit) {
    .Call(`_fgRcppNorway_canopy_breadth_fun_cpp`, cr_width, uguess, n_drag, c_drag, drag_upper_limit)
}

max_gap_factor_fun_cpp <- function(gap_size, ht) {
    .Call(`_fgRcppNorway_max_gap_factor_fun_cpp`, gap_size, ht)
}

edge_gap_gust_factor_fun_cpp <- function(spacing, mean_ht, dist_edge, gap_size, fgr_constants) {
    .Call(`_fgRcppNorway_edge_gap_gust_factor_fun_cpp`, spacing, mean_ht, dist_edge, gap_size, fgr_constants)
}

edge_gap_factor_fun_cpp <- function(spacing, equivalent_mean_ht, dist_edge, gap_size, fgr_constants) {
    .Call(`_fgRcppNorway_edge_gap_factor_fun_cpp`, spacing, equivalent_mean_ht, dist_edge, gap_size, fgr_constants)
}

tc_intercept_fun_cpp <- function(dbh, ht, ci, ci_value) {
    .Call(`_fgRcppNorway_tc_intercept_fun_cpp`, dbh, ht, ci, ci_value)
}

tc_zero_intercept_fun_cpp <- function(dbh, ht, ci, ci_value) {
    .Call(`_fgRcppNorway_tc_zero_intercept_fun_cpp`, dbh, ht, ci, ci_value)
}

tc_zero_intercept_new_bal_fun_cpp <- function(dbh, ht, ci, ci_value) {
    .Call(`_fgRcppNorway_tc_zero_intercept_new_bal_fun_cpp`, dbh, ht, ci, ci_value)
}

tc_zero_intercept_fun_balBA_cpp <- function(dbh, ht, ci, ci_value) {
    .Call(`_fgRcppNorway_tc_zero_intercept_fun_balBA_cpp`, dbh, ht, ci, ci_value)
}

critical_moment_breakage_rou_cpp <- function(dbh, mor, fknot) {
    .Call(`_fgRcppNorway_critical_moment_breakage_rou_cpp`, dbh, mor, fknot)
}

critical_moment_breakage_tmc_cpp <- function(dbh, ht, cr_depth, mor, fknot) {
    .Call(`_fgRcppNorway_critical_moment_breakage_tmc_cpp`, dbh, ht, cr_depth, mor, fknot)
}

critical_moment_overturning_cpp <- function(c_reg, stem_density, stem_vol) {
    .Call(`_fgRcppNorway_critical_moment_overturning_cpp`, c_reg, stem_density, stem_vol)
}

lambdacapital_fun_cpp <- function(cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit) {
    .Call(`_fgRcppNorway_lambdacapital_fun_cpp`, cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit)
}

gammasolved_fun_cpp <- function(cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, fgr_constants) {
    .Call(`_fgRcppNorway_gammasolved_fun_cpp`, cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, fgr_constants)
}

zpd_fun_cpp <- function(cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants) {
    .Call(`_fgRcppNorway_zpd_fun_cpp`, cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants)
}

z0_fun_cpp <- function(cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants) {
    .Call(`_fgRcppNorway_z0_fun_cpp`, cr_width, cr_depth, spacing, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants)
}

tm_ratio_cpp <- function(spacing_before, spacing_current, years_since_thin, cr_width, cr_depth, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants) {
    .Call(`_fgRcppNorway_tm_ratio_cpp`, spacing_before, spacing_current, years_since_thin, cr_width, cr_depth, uguess, n_drag, c_drag, drag_upper_limit, ht, fgr_constants)
}

tm_ratio_ci_cpp <- function(spacing_before, spacing_current, years_since_thin, cr_width, cr_depth, uguess, n_drag, c_drag, drag_upper_limit, ht, ci, fgr_constants) {
    .Call(`_fgRcppNorway_tm_ratio_ci_cpp`, spacing_before, spacing_current, years_since_thin, cr_width, cr_depth, uguess, n_drag, c_drag, drag_upper_limit, ht, ci, fgr_constants)
}

tm_ratio_simple_cpp <- function(spacing_before, spacing_current, years_since_thin) {
    .Call(`_fgRcppNorway_tm_ratio_simple_cpp`, spacing_before, spacing_current, years_since_thin)
}

tm_ratio_simple_ci_cpp <- function(spacing_before, spacing_current, years_since_thin, ci) {
    .Call(`_fgRcppNorway_tm_ratio_simple_ci_cpp`, spacing_before, spacing_current, years_since_thin, ci)
}

bending_moment_rou_cpp <- function(dbh, ht, cr_width, cr_depth, spacing, dist_edge, gap_size, uguess, n_drag, c_drag, drag_upper_limit, ro, fgr_constants, aerodynamic_ht) {
    .Call(`_fgRcppNorway_bending_moment_rou_cpp`, dbh, ht, cr_width, cr_depth, spacing, dist_edge, gap_size, uguess, n_drag, c_drag, drag_upper_limit, ro, fgr_constants, aerodynamic_ht)
}

force_of_wind_fun_cpp <- function(bm, ht, cr_depth) {
    .Call(`_fgRcppNorway_force_of_wind_fun_cpp`, bm, ht, cr_depth)
}

r_fun_cpp <- function(lever_arm, pull_height) {
    .Call(`_fgRcppNorway_r_fun_cpp`, lever_arm, pull_height)
}

i_fun_cpp <- function(dbh, ht, cr_depth) {
    .Call(`_fgRcppNorway_i_fun_cpp`, dbh, ht, cr_depth)
}

deflection_fun_cpp <- function(x, lever_arm, fow, dbh, ht, cr_depth, pull_height, moe, fgr_constants) {
    .Call(`_fgRcppNorway_deflection_fun_cpp`, x, lever_arm, fow, dbh, ht, cr_depth, pull_height, moe, fgr_constants)
}

dlf_fun_Norway_cpp <- function(bm, ht, cr_depth, cr_width, cr_prarea, crown_off, stem_vol, dbh, moe, crown_density, stem_density, snow_load, fgr_constants) {
    .Call(`_fgRcppNorway_dlf_fun_Norway_cpp`, bm, ht, cr_depth, cr_width, cr_prarea, crown_off, stem_vol, dbh, moe, crown_density, stem_density, snow_load, fgr_constants)
}

uh_breakage_rou_Norway_cpp <- function(mean_ht, mean_dbh, spacing, dist_edge, gap_size, mean_cr_width, mean_cr_depth, mean_cr_prarea, crown_off, moe, mor, fknot, n_drag, c_drag, drag_upper_limit, stem_vol, stem_density, crown_density, snow_load, ro, fgr_constants, aerodynamic_ht) {
    .Call(`_fgRcppNorway_uh_breakage_rou_Norway_cpp`, mean_ht, mean_dbh, spacing, dist_edge, gap_size, mean_cr_width, mean_cr_depth, mean_cr_prarea, crown_off, moe, mor, fknot, n_drag, c_drag, drag_upper_limit, stem_vol, stem_density, crown_density, snow_load, ro, fgr_constants, aerodynamic_ht)
}

uh_breakage_tmc_Norway_cpp <- function(tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, moe, mor, fknot, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, n_drag, c_drag, drag_upper_limit, equivalent_mean_ht, stand_cr_depth, stand_cr_width, fgr_constants, aerodynamic_ht) {
    .Call(`_fgRcppNorway_uh_breakage_tmc_Norway_cpp`, tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, moe, mor, fknot, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, n_drag, c_drag, drag_upper_limit, equivalent_mean_ht, stand_cr_depth, stand_cr_width, fgr_constants, aerodynamic_ht)
}

uh_breakage_tmc_tmr_simple_Norway_cpp <- function(tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, equivalent_mean_ht, moe, mor, fknot, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, fgr_constants) {
    .Call(`_fgRcppNorway_uh_breakage_tmc_tmr_simple_Norway_cpp`, tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, equivalent_mean_ht, moe, mor, fknot, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, fgr_constants)
}

uh_overturning_rou_Norway_cpp <- function(mean_ht, mean_dbh, spacing, dist_edge, gap_size, mean_cr_width, mean_cr_depth, mean_cr_prarea, crown_off, moe, c_reg, n_drag, c_drag, drag_upper_limit, stem_vol, stem_density, crown_density, snow_load, ro, fgr_constants, aerodynamic_ht) {
    .Call(`_fgRcppNorway_uh_overturning_rou_Norway_cpp`, mean_ht, mean_dbh, spacing, dist_edge, gap_size, mean_cr_width, mean_cr_depth, mean_cr_prarea, crown_off, moe, c_reg, n_drag, c_drag, drag_upper_limit, stem_vol, stem_density, crown_density, snow_load, ro, fgr_constants, aerodynamic_ht)
}

uh_overturning_tmc_Norway_cpp <- function(tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, moe, c_reg, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, n_drag, c_drag, drag_upper_limit, equivalent_mean_ht, stand_cr_depth, stand_cr_width, fgr_constants, aerodynamic_ht) {
    .Call(`_fgRcppNorway_uh_overturning_tmc_Norway_cpp`, tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, moe, c_reg, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, n_drag, c_drag, drag_upper_limit, equivalent_mean_ht, stand_cr_depth, stand_cr_width, fgr_constants, aerodynamic_ht)
}

uh_overturning_tmc_tmr_simple_cpp <- function(tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, equivalent_mean_ht, moe, c_reg, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, fgr_constants) {
    .Call(`_fgRcppNorway_uh_overturning_tmc_tmr_simple_cpp`, tree_ht, dbh, cr_depth, cr_width, cr_prarea, crown_off, spacing_current, spacing_before, years_since_thin, dist_edge, gap_size, equivalent_mean_ht, moe, c_reg, stem_vol, stem_density, crown_density, snow_load, ci, ci_value, fgr_constants)
}

csw_Norway_cpp <- function(tree_ht, tree_dbh, crown_weight, cr_depth, moe, grav) {
    .Call(`_fgRcppNorway_csw_Norway_cpp`, tree_ht, tree_dbh, crown_weight, cr_depth, moe, grav)
}

elevate_cpp <- function(uh, z0, d, ht, ht_above_d) {
    .Call(`_fgRcppNorway_elevate_cpp`, uh, z0, d, ht, ht_above_d)
}

uh_breakage_heightz_cpp <- function(uh_b, tree_ht, cr_depth, dbh, m = 2.0/3.0) {
    .Call(`_fgRcppNorway_uh_breakage_heightz_cpp`, uh_b, tree_ht, cr_depth, dbh, m)
}

fg_rou_Norway_cpp <- function(inputdata_full, fgr_constants, species_parameters, full_output_ = NULL, breakage_basecanopy = "no") {
    .Call(`_fgRcppNorway_fg_rou_Norway_cpp`, inputdata_full, fgr_constants, species_parameters, full_output_, breakage_basecanopy)
}

fg_tmc_Norway_cpp <- function(inputdata_full, fgr_constants, species_parameters, full_output_ = NULL, breakage_basecanopy = "no") {
    .Call(`_fgRcppNorway_fg_tmc_Norway_cpp`, inputdata_full, fgr_constants, species_parameters, full_output_, breakage_basecanopy)
}

